# Site settings
title: 职业杂谈
description: '让职业生活多些经历少些迷茫' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aegooooon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/new/logo-text-dark2.svg"
logo-icon: "/assets/img/branding/new/logo-icon-dark.svg"
logo-icon-SEO: "/assets/img/branding/new/PNG-logo-icon-dark.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/new/logo-text-light2.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: 访谈小组 # add your name
author-pic: logo-icon-dark.svg
about-author: 愿大家对职业生活多些认知，少些迷茫。愿大家对职业生活多些认知，少些迷茫。愿大家对职业生活多些认知，少些迷茫。愿大家对职业生活多些认知，少些迷茫。愿大家对职业生活多些认知，少些迷茫。愿大家对职业生活多些认知，少些迷茫。

# Contact links
email: 3062018430@qq.com # Add your Email address
phone: # +852 59380790
website: https://aegooooon.github.io # Add your website
linkedin: aegooooon # Add your Linkedin handle
github: aegooooon # Add your Github handle
twitter: '@MvmThe' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: giscus  #[disqus, utteranc, giscus]
comments_opts:
  # Utteranc
  utteranc_repo: "" # The GitHub repo URL for utteranc, e.g., "owner/repo"
  utteranc_issue_term: "" # The GitHub issue label for utteranc
  utteranc_label: "" # The GitHub comments label for utteranc
  utteranc_theme: "" # The GitHub comment's theme for utteranc, e.g. github-dark
  
  # Giscus
  giscus_repo: "Aegooooon/Aegooooon.github.io"
  giscus_repo_id: "R_kgDOMsVIHA"
  giscus_mapping: "pathname"
  giscus_theme: "light_high_contrast"

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
